### ISSUE TITLE
ModuleNotFoundError: No module named 'Cryptodome'

### ISSUE THREAD

**Issue by ghost** [SoulMelody/hls-get#1]
Within download.py, line 11 states
`from Cryptodome.Cipher import AES`

Latest version is 3.8.1, and according to website examples from pycryptodome [here](https://www.pycryptodome.org/en/latest/src/examples.html), this should be stated as
`from Crypto.Cipher import AES`

Changing the line to remove 'dome' allows command to correctly initialise.

**Comment by SoulMelody** [comment]
OK, fixed.
